// Generated by https://quicktype.io
export interface AllArticlesDTO {
  allArticles: AllArticle[];
  _allArticlesMeta: AllArticlesMeta;
}

export interface AllArticle {
  thumbnail: Thumbnail;
  title: string;
  tag: string;
  articleDescription: string;
  slug: string;
}

interface AllArticlesMeta {
  count: number;
}

interface Thumbnail {
  url: string;
}
