// Generated by https://quicktype.io
export interface AllArticlesDTO {
  allArticles: AllArticle[];
  _allArticlesMeta: AllArticlesMeta;
}

export interface AllArticle {
  thumbnail: Thumbnail;
  title: string;
  tag: string;
  articleDescription: string;
  slug: string;
}

interface AllArticlesMeta {
  count: number;
}

interface Thumbnail {
  url: string;
}

export interface ArticleDTO {
  article: Article;
}

interface Article {
  id: string;
  thumbnail: Thumbnail;
  title: string;
  tag: string;
  author: Author;
  updatedAt: string;
  viewscount: number;
  body: string;
  reference: string;
  slug: string;
}

interface Author {
  authorName: string;
  linkedinLink: string;
}
