export default interface DatoDTO<T> {
  data: T;
  errors?: Error[];
}

// Generated by https://quicktype.io
interface Error {
  message: string;
  locations: Location[];
  path: string[];
  extensions: Extensions;
}

export interface Extensions {
  code: string;
  typeName: string;
  fieldName: string;
}

export interface Location {
  line: number;
  column: number;
}
